-- Migrate a restored legacy database to the current career-guidance schema.
-- Run with psql -v ON_ERROR_STOP=1 against a COPY of the source database.

BEGIN;

LOCK TABLE account, role, account_roles, pupil, specialist, prediction,
    psych_test_type, vr_test_type IN SHARE ROW EXCLUSIVE MODE;

CREATE TABLE IF NOT EXISTS school (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL UNIQUE,
    address VARCHAR(500),
    email VARCHAR(200),
    phone VARCHAR(50)
);

ALTER TABLE pupil ADD COLUMN IF NOT EXISTS school_id BIGINT;

-- One canonical school row per case-insensitive trimmed legacy value. The
-- original pupil.school text remains untouched for audit and rollback.
INSERT INTO school (name)
SELECT candidate.name
FROM (
    SELECT LOWER(TRIM(p.school)) AS normalized_name,
           MIN(TRIM(p.school)) AS name
    FROM pupil p
    WHERE NULLIF(TRIM(p.school), '') IS NOT NULL
    GROUP BY LOWER(TRIM(p.school))
) candidate
WHERE NOT EXISTS (
    SELECT 1
    FROM school s
    WHERE LOWER(s.name) = candidate.normalized_name
)
ON CONFLICT (name) DO NOTHING;

UPDATE pupil p
SET school_id = (
    SELECT MIN(s.id)
    FROM school s
    WHERE LOWER(s.name) = LOWER(TRIM(p.school))
)
WHERE p.school_id IS NULL
  AND NULLIF(TRIM(p.school), '') IS NOT NULL;

DO $migration$
BEGIN
    IF NOT EXISTS (
        SELECT 1
        FROM pg_constraint
        WHERE conrelid = 'pupil'::regclass
          AND conname = 'fk_pupil_school'
    ) THEN
        ALTER TABLE pupil
            ADD CONSTRAINT fk_pupil_school
            FOREIGN KEY (school_id) REFERENCES school(id);
    END IF;
END
$migration$;

CREATE INDEX IF NOT EXISTS idx_pupil_school_id ON pupil(school_id);

CREATE TABLE IF NOT EXISTS curator (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    patronymic VARCHAR(50),
    account_id BIGINT NOT NULL UNIQUE,
    school_id BIGINT NOT NULL,
    CONSTRAINT fk_curator_account FOREIGN KEY (account_id) REFERENCES account(id),
    CONSTRAINT fk_curator_school FOREIGN KEY (school_id) REFERENCES school(id)
);

CREATE INDEX IF NOT EXISTS idx_curator_school_id ON curator(school_id);

INSERT INTO role (name)
VALUES ('CURATOR')
ON CONFLICT (name) DO NOTHING;

ALTER TABLE psych_test_type
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE vr_test_type
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE prediction
    ADD COLUMN IF NOT EXISTS cluster INTEGER,
    ADD COLUMN IF NOT EXISTS distance DOUBLE PRECISION,
    ADD COLUMN IF NOT EXISTS confidence_category VARCHAR(255),
    ADD COLUMN IF NOT EXISTS predicted_profession_id BIGINT,
    ADD COLUMN IF NOT EXISTS nearest_specialist_id BIGINT;

DO $migration$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'prediction'::regclass
          AND conname = 'fk_prediction_profession'
    ) THEN
        ALTER TABLE prediction
            ADD CONSTRAINT fk_prediction_profession
            FOREIGN KEY (predicted_profession_id) REFERENCES profession(id);
    END IF;

    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint
        WHERE conrelid = 'prediction'::regclass
          AND conname = 'fk_prediction_specialist'
    ) THEN
        ALTER TABLE prediction
            ADD CONSTRAINT fk_prediction_specialist
            FOREIGN KEY (nearest_specialist_id) REFERENCES specialist(id);
    END IF;
END
$migration$;

CREATE INDEX IF NOT EXISTS idx_prediction_profession_id
    ON prediction(predicted_profession_id);
CREATE INDEX IF NOT EXISTS idx_prediction_specialist_id
    ON prediction(nearest_specialist_id);

-- This table belongs to the removed B2B invitation contour. The source dump
-- contains no rows. Refuse the drop if another dump contains any data.
DO $migration$
DECLARE
    invitation_count BIGINT;
BEGIN
    IF TO_REGCLASS('public.invitation') IS NOT NULL THEN
        EXECUTE 'SELECT COUNT(*) FROM invitation' INTO invitation_count;
        IF invitation_count <> 0 THEN
            RAISE EXCEPTION
                'Refusing to drop invitation: % row(s) must be reviewed',
                invitation_count;
        END IF;
        EXECUTE 'DROP TABLE invitation';
    END IF;
END
$migration$;

COMMIT;
