-- Additive migration for the career-guidance deployment.
-- Apply only to a restored copy of the source database after backup.

CREATE TABLE IF NOT EXISTS school (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(200) NOT NULL UNIQUE,
    address VARCHAR(500),
    email VARCHAR(200),
    phone VARCHAR(50)
);

ALTER TABLE pupil ADD COLUMN IF NOT EXISTS school_id BIGINT;

-- Preserve the existing free-text school values and establish structured links.
INSERT INTO school (name)
SELECT candidate.name
FROM (
    SELECT LOWER(TRIM(p.school)) AS normalized_name,
           MIN(TRIM(p.school)) AS name
    FROM pupil p
    WHERE NULLIF(TRIM(p.school), '') IS NOT NULL
    GROUP BY LOWER(TRIM(p.school))
) candidate
WHERE NOT EXISTS (
    SELECT 1 FROM school s
    WHERE LOWER(s.name) = candidate.normalized_name
)
ON CONFLICT (name) DO NOTHING;

UPDATE pupil p
SET school_id = (
    SELECT MIN(s.id)
    FROM school s
    WHERE LOWER(TRIM(p.school)) = LOWER(s.name)
)
WHERE p.school_id IS NULL
  AND p.school IS NOT NULL
  AND NULLIF(TRIM(p.school), '') IS NOT NULL;

DO $$
BEGIN
    IF NOT EXISTS (
        SELECT 1 FROM pg_constraint WHERE conname = 'fk_pupil_school'
    ) THEN
        ALTER TABLE pupil
            ADD CONSTRAINT fk_pupil_school
            FOREIGN KEY (school_id) REFERENCES school(id);
    END IF;
END $$;

CREATE INDEX IF NOT EXISTS idx_pupil_school_id ON pupil(school_id);

CREATE TABLE IF NOT EXISTS curator (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(50) NOT NULL,
    surname VARCHAR(50) NOT NULL,
    patronymic VARCHAR(50),
    account_id BIGINT NOT NULL UNIQUE,
    school_id BIGINT NOT NULL,
    CONSTRAINT fk_curator_account FOREIGN KEY (account_id) REFERENCES account(id),
    CONSTRAINT fk_curator_school FOREIGN KEY (school_id) REFERENCES school(id)
);

CREATE INDEX IF NOT EXISTS idx_curator_school_id ON curator(school_id);

INSERT INTO role (name)
VALUES ('CURATOR')
ON CONFLICT (name) DO NOTHING;

ALTER TABLE psych_test_type
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;

ALTER TABLE vr_test_type
    ADD COLUMN IF NOT EXISTS is_active BOOLEAN NOT NULL DEFAULT TRUE;
